### PR TITLE
Aesthetics

### LINKED ISSUE #51: Issues with target selector
Adding `?targetSelector=lf-*` to a handbook URL can be used to select a particular target, but the target selector remains unaffected (meaning it could point to the wrong target).

On a related note, we might want to make the selected target part of the URL because otherwise it becomes difficult to share handbook URLs. If I'm looking at the Python documentation and copy the URL to a friend, and they happen to have selected C as the current target language, they will see a different page when they follow my link.

### LINKED ISSUE #52: Mobile view needs to be improved
The changes to the main menu bar don't translate well to the mobile view. Either we have to revert these changes or have a special case with a smaller logo.

### LINKED ISSUE #75: Color scheme: Purge #3178c6
I mean this shade of blue:

TypeScript

This color already "belongs" to TypeScript: It's recognizably a TS color.

I'm posting this as an issue rather than trying to solve it myself because I do think it is a little complicated and important. To my knowledge, LF has specific shades of orange and dark blue, respectively, but no light blue. We could add another color, but maybe that would be excessive. And if we restrict ourselves to the existing colors, which are too strong and dark to use in large quantities, then our front page might require some redesign.

### PR DESCRIPTION
**Pull request by petervdonovan**
This PR includes a number of small changes:
* Adjust color palette (fixes #75)
* Make the target selector behave more like the other parts of the navigation sidebar
* Link target selector with query parameters in the URL (fixes #51)
* Make the header logo responsive to screen size (fixes #52)
* Make the footer restructure properly on small screens
* Re-enable the sticky navigation script that hides the horizontal navigation bar when scrolling down on mobile

I think this addresses everything I talked about with @lhstrh yesterday. Please let me know if more little adjustments are needed here!

### CODE REVIEW

File: packages/lingua-franca/gatsby-browser.js [hunk 1]
```diff
@@ -1,11 +1,6 @@
 // This hooks ups client-side app analytics
 // it's based on how the google analytics plugin works for gatsby
 // https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-google-analytics/src/gatsby-browser.js
-const { setInitialTargetLanguage } = require("./src/lib/setInitialTargetLanguage")
-
-exports.onClientEntry = () => {
-  window.onload = () => { setInitialTargetLanguage() }
-}
 
 exports.onRouteUpdate = ({ location, prevLocation }) => {
```
Comment (lhstrh) [inline packages/lingua-franca/gatsby-browser.js:5]: @petervdonovan, could this be the cause for #90?

Comment (petervdonovan) [reply packages/lingua-franca/gatsby-browser.js:5]: That seems possible.

When I was doing #91 I realized that when this branch was merged, `setInitialTargetLanguage()` invocations appeared in several places. I had let this by because I did not (and still do not) really understand when Gatsby calls everything and where different setup processes should go (and because I did not do due diligence in reviewing my work before the merge).

I think the solution in #91 "should work" based on the [documentation](https://www.gatsbyjs.com/docs/reference/config-files/gatsby-browser/#onRouteUpdate). I do not understand how it would work to just have `setInitialTargetLanguage()` hooked onto `onClientEntry` because the target language should be set whenever the user navigates to a different page, but given the other places where `setInitialTargetLanguage()` was invoked, maybe they were collectively sufficient.
